### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by ReubenDo** [IMSY-DKFZ/htc#1]
Hi there,

Thank you for your work!

Will the dataset be made publicly available?

Regards,
Reuben

**Comment by SilviaSeidlitz** [comment]
Dear Reuben, 

thank you very much for your interest! Our medical collaboration partners are in the process of preparing a dedicated data set paper, comprising also the data from this study. We'll make sure to link the data here as well, once it is publicly available.

Best regards,
Silvia
